apiVersion: v1
kind: ReplicationController
metadata:
  name: intruder-frontend--0-0-1-app-v2
  namespace: intruder
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: kube-app-v2
    spec:
      containers:
      - name: app-v2
        image: 127.0.0.1:5000/intruder/kube_app_v2:0.0.1
        ports:
        - containerPort: 8080